version: '3.1' #format version for this docker compose file
services:
  mongodb:
    image: mongo:latest
    environment: {}
    ports:
      - "27017:27017"
    command: mongod
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "topic-first:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  apiserver:
    image: bennyaf/apiserver
    ports:
      -  "3000:3000"
    environment:
      HOSTIP: ${HOST_IP}
    depends_on:
      - kafka
      - mongodb
  webserver:
    image: bennyaf/webserver
    ports:
      -  "3001:3001"
    depends_on:
        - kafka
        - mongodb
  client:
    image: bennyaf/client
    ports:
      -  "4200:80"
    depends_on:
        - kafka
        - mongodb
    